### ISSUE TITLE
Alt+Up and Alt+Down for prev and next difference

### ISSUE THREAD

**Issue by techtonik** [blais/xxdiff#12]
As a WinMerge refugee I'd like to use Alt+Up and Alt+Down for navigating changes. https://manual.winmerge.org/en/Shortcut_keys.html

However, I don't see how to add a second shortcut for the same function.

https://github.com/blais/xxdiff/blob/30b44034e5cc2665f7fc44ce45da7252d46cbe17/src/resources.cpp#L138-L139

**Comment by blais** [comment]
These can be overridden in the configuration file.
See --list-resources

**Comment by techtonik** [comment]
From http://furius.ca/xxdiff/doc/xxdiff-doc.html#resource-reference

1. create **`.xxdiffrc`**
2. add line `Accel.NextUnselected: "<key>"`

What should the `"<key>"` for Alt+Up look like?
