### ISSUE TITLE
convert xxdiff-scripts to Python3

### ISSUE THREAD

**Issue by calestyo** [blais/xxdiff#13]
Hey.

Python2 is about to reach it's end. Any plans to migrate the xx-* scripts to Python3?

Cheers,
Chris.

**Comment by blais** [comment]
Would love to, but so little time. Send me a patch?

**Comment by tatarsky** [comment]
This is an old issue but if it helps anyone also building when I built the python modules using a python3.8.12 virtualenv the person we built it for has not yet hit anything that didn't work. Please note though that the primary script was xx-svn-diff.

**Comment by blais** [comment]
Pretty sure it's all ported.
I just ran lib2to3 on it and has no material changes.
Closing.
