### ISSUE TITLE
xxdiff hangs on quit

### ISSUE THREAD

**Issue by vicn1222** [blais/xxdiff#22]
I am using CentOS 7 and 8 with Qt5.

In both platforms, when I try to quit xxdiff, it hangs very often. Sometime it does quit immediately. I don't know why.

I made the below changes, it quits immediately with this changes.

Can someone familiar with the codes please review my changes? Changes are in "app.cpp". It could be a Qt bug...

Thank you and great work!

<pre>
      // Note: on OSX, this action is reaffected to the Quit item of the application
      // menu, which always has Ctrl-Q as an accelerator. This can be prevented by
      //  using setMenuRole( QAction::ApplicationSpecificRole ), or our item can even
      // be kept out of the application menu with QAction::NoRole, but anyway, there
      // will be a standard Quit item in the application menu with Ctrl-Q.
/*
      fileMenu->addAction(
         "Exit", this, SLOT(quit()),
         _resources->getAccelerator( ACCEL_EXIT )
      );
*/
     QAction* quitAction = new QAction( this );
     fileMenu->addAction( quitAction );
     quitAction->setText( tr( "Exit" ) );
     quitAction->setShortcut( _resources->getAccelerator( ACCEL_EXIT ) );
     connect( quitAction, SIGNAL( triggered() ), this, SLOT( quit() ) );
</pre>

**Comment by blais** [comment]
As mentioned in the commit, I don't quite understand why using the triggered action makes a difference, but given the level of maintenance I do on this over the past few years, well, I tested the change and it doesn't break anything. Thanks for isolating this.

Glad the tool is of continued help to you.
