### ISSUE TITLE
Can one xxdiff two directories and only include certain files?

### ISSUE THREAD

**Issue by mathomp4** [blais/xxdiff#24]
As the subject says, I was wondering if one can use `xxdiff` to compare two directories but only compare matching files? Say I want to `xxdiff` all the `.rc` files in `dir1/` and `dir2/`?

My guess is probably not (since GNU `diff` doesn't seem to be able to do this), but I thought I'd ask.

**Comment by blais** [comment]
$ xxdiff --help
xxdiff (cmdline.cpp:454): 
Usage: xxdiff [OPTIONS] file1 file2 [file3]

[..]

  --exclude, -e <arg>        When comparing directories, ignore files and 
                             subdirectories whose basenames match pattern. 

  --exclude-from <arg>       When comparing directories, ignore files and 
                             subdirectories whose basenames match any pattern 
                             contained in file.
