### ISSUE TITLE
asprintf for titles breaks double clicking on files/dirs

### ISSUE THREAD

**Issue by andreasbaumann** [blais/xxdiff#30]
This is master, version 090aa680265e77812ed8faa75482ec8efdb44913, on Archlinux
(happens when compiled with Qt 5.15.10 or Qt 6.3.2)

When I click on a deep diff of two directories onto a directory or a file to diff, I get:

```
xxdiff (cmdline.cpp:768): 
You can specify at most 3 filenames.
Extra arguments: " "
Use 'xxdiff --help' for more information.
```

This is because excess titles with a newline are passed to the subprocess xxdiff when opening the two dirs/files.

I could track it down to:

app.cpp:3578:
```
      XxUtil::splitArgs( command, titles, filenames, executable, args );
```

app.cpp:3534:
```
             tmpTitle->asprintf( "--title%d=%s",
                                ii+1,
                                _cmdline._userFilenames[ii].toLocal8Bit().constData() );
```

Changing the asprintf to sprintf (for Qt5) makes it work again.

Not sure if it breaks everywhere and I'm not convinced that this should be changed back to sprintf (which doesn't exist on Qt6?).

Can anybody else also reproduce this?

**Comment by jdkloe** [comment]
This is confirmed on my side as well. I have the same problem after upgrading the the latest git master verison.
(commit from 5-Sep-2022;  https://github.com/blais/xxdiff/commit/090aa680265e77812ed8faa75482ec8efdb44913).
My system is Fedora 36, and I compiled with qt5 5.15.5.

**Comment by jdkloe** [comment]
The bugffix as suggested by @andreasbaumann works on my side as well and solves the problem.

**Comment by andreasbaumann** [comment]
Thanks for confirming (I thought I was alone).. :-)

Don't get me wrong: I don't think using sprintf instead of asprintf is the final solution, especially because Qt6 deprecated
QString.sprintf:

```
app.cpp:3534:31: warning: ‘QString& QString::sprintf(const char*, ...)’ is deprecated: Use asprintf(), arg() or QTextStream instead [-Wdeprecated-declarations]
```

So it's a good thing to have moved to non-deprecated functions..

Qt seems not so sure about asprintf either as mentioned on https://doc.qt.io/qt-6/qstring.html:

```
Warning: We do not recommend using QString::asprintf() in new Qt code. Instead, consider using [QTextStream](https://doc.qt.io/qt-6/qtextstream.html) or [arg](https://doc.qt.io/qt-6/qstring.html#arg)(), both of which support Unicode strings seamlessly and are type-safe. Here is an example that uses [QTextStream](https://doc.qt.io/qt-6/qtextstream.html):
```

But this would be a much bigger change to the code everywhere..

I'll try to dig deeper and see why it is failing with asprintf, maybe this is just a corner case, because everywhere else it works
in the code, just not for the titles..

**Comment by andreasbaumann** [comment]
Ok, as I read the Qt 5 source code:

```
QString QString::asprintf(const char *cformat, ...)
{
    va_list ap;
    va_start(ap, cformat);
    const QString s = vasprintf(cformat, ap);
    va_end(ap);
    return s;
}
```

and:

```
QString &QString::sprintf(const char *cformat, ...)
{
    va_list ap;
    va_start(ap, cformat);
    *this = vasprintf(cformat, ap);
    va_end(ap);
    return *this;
}
```

sprintf modified the current qstring (tmpTitle) and asprintf returns a QString.
So tmpTitle will always be empty if using asprintf!

The following change in app.cpp illustrates this:

```
         // Add the title there if we have it.
         if ( 0 > _cmdline._userFilenames[ii].indexOf('%') ) {
             QString * tmpTitle = new QString();
             QString s = tmpTitle->asprintf( "--title%d=%s",
                                ii+1,
                                _cmdline._userFilenames[ii].toLocal8Bit().constData() );
fprintf( stderr, "s: %s\n", s.toStdString().c_str() );
fprintf( stderr, "tmpTitle: %s\n", tmpTitle->toStdString().c_str() );
//             titles[ii] = tmpTitle;
         }
      }
```

This gives:

```
s: --title1=
tmpTitle: 
s: --title2=
tmpTitle: 
```

when clicking on a file/dir to compare.

This looks more sane to me (minus potential memory leaks):

```
         if ( 0 > _cmdline._userFilenames[ii].indexOf('%') ) {
             QString s = QString::asprintf( "--title%d=%s",
                                ii+1,
                                _cmdline._userFilenames[ii].toLocal8Bit().constData() );
             titles[ii] = new QString( s );
         }
```

Also the asprintf in util.cpp (formatPrintFunc) is has likely the same issue..

**Comment by andreasbaumann** [comment]
IMHO Qt made a strange move by having sprintf as a member function and asprintf a static member function, but oh well.. :-)

**Comment by blais** [comment]
Thanks everyone. 

I just checked the source now and this is a change that was introduced by a user patch recently to upgrade to Qt6 and I didn't catch it. Mark one more for the devil that counts all the problems due to the absence of unit tests (and blame me for that).

I'm not sure why ::sprintf() was removed (it's probably something due to unicode). Changing those uses to libc sprintf() would probably be okay because we're not really supporting unicode in any of these uses.

Even better I could maybe use the QTextStream instead, my code is ancient, when I look at it I can't help but think "was I really that stupid?" Those lines are from 2005. *sheesh*
I'll give it 15 minutes, see if I can pull it off

**Comment by blais** [comment]
I just submitted a fix. Unfortunately still using asprintf(). I'd have to find a non-Qt replacement, using the stream functions would require rewriting all that gnarly caller code. 
My goodness.... this whole thing needs a rewrite from scratch...

Seem to work. Your code review appreciated.

**Comment by andreasbaumann** [comment]
Can confirm: it works fine, thanks for fixing this. :-)
Retested it with Qt5 and Qt6.
xxdiff is my daily merging driver since many years (I don't know since when, I lost count, but it was before the rewrite to the Qt framework). Thanks for that. :-)

**Comment by blais** [comment]
I think it was born on Qt, it must have been xdiff on sgi. 90s!

My quick thoughts : I desperately want xxdiff for the console with all of
its features. I've been using tmux for many years now and switched to using
an unsatisfactory emacs based back I built. The console compromise is
really worth it. I should build a better diff for emacs

**Comment by andreasbaumann** [comment]
The xdiff version on Solaris, I think, that was it. :-)
http://sgifiles.irixnet.org/sgi/xdiff/xdiff/
