### ISSUE TITLE
github releases (tags) for versions?

### ISSUE THREAD

**Issue by christophprokop** [blais/xxdiff#31]
Hi there,

would it be possible to tag commits which change the content of the VERSION file?
e.g. cfc6275 bumped to version 5.1

Greetings and thanks a lot!
c

**Comment by blais** [comment]
xxdiff does not tag versions. 
This is a very old project in indefinite maintenance mode.
I will continue maintaining it and doing minor upgrades due to changes from its dependencies.
The latest commit on branch 'master' is always the most stable.
